def get_credentials():
    try:
        f = open("userinfo.txt", "r")
        content = f.readlines()
        ic_user = content[0].rstrip()
        ic_pw = content[1].rstrip()
        destiny_user = content[2].rstrip()
        destiny_pw = content[3].rstrip()
        email = content[4].rstrip()
        email_pw = content[5].rstrip()
        f.close()
        return(ic_user, ic_pw, destiny_user, destiny_pw, email, email_pw)
        
    except:
        f = open("userinfo.txt", "wt")
        ic_user = input("Enter your IC username: ")
        f.write(ic_user + "\n")
        ic_pw = input("Enter your IC password: ")
        f.write(ic_pw + "\n")
        destiny_user = input("Enter your destiny username: ")
        f.write(destiny_user + "\n")
        destiny_pw = input("Enter your destiny password: ")
        f.write(destiny_pw + "\n")
        email = input("Enter your full email address: ")
        f.write(email + "\n")
        email_pw = input("Enter your email password: ")
        f.write(email_pw + "\n")
        f.close()
        return(ic_user, ic_pw, destiny_user, destiny_pw, email, email_pw)